swagger: '2.0'
schemes:
  - https
host: api.spotify.com
basePath: /v1
info:
  title: Spotify
  version: v1
  x-apisguru-categories:
    - media
  x-logo:
    url: 'https://api.apis.guru/v2/cache/logo/https_logo-core.clearbit.com_spotify.com'
  x-origin:
    - format: raml
      url: 'https://raw.githubusercontent.com/spotify/web-api/master/specifications/raml/api.raml'
      version: '0.8'
  x-preferred: true
  x-providerName: spotify.com
securityDefinitions:
  oauth_2_0_accessCode:
    authorizationUrl: 'https://accounts.spotify.com/authorize'
    description: |
      Spotify supports OAuth 2.0 for authenticating all API requests.
    flow: accessCode
    scopes:
      playlist-modify-private: ''
      playlist-modify-public: ''
      playlist-read-collaborative: ''
      playlist-read-private: ''
      user-follow-modify: ''
      user-follow-read: ''
      user-library-modify: ''
      user-library-read: ''
      user-read-birthdate: ''
      user-read-email: ''
      user-read-private: ''
    tokenUrl: 'https://accounts.spotify.com/api/token'
    type: oauth2
  oauth_2_0_implicit:
    authorizationUrl: 'https://accounts.spotify.com/authorize'
    description: |
      Spotify supports OAuth 2.0 for authenticating all API requests.
    flow: implicit
    scopes:
      playlist-modify-private: ''
      playlist-modify-public: ''
      playlist-read-collaborative: ''
      playlist-read-private: ''
      user-follow-modify: ''
      user-follow-read: ''
      user-library-modify: ''
      user-library-read: ''
      user-read-birthdate: ''
      user-read-email: ''
      user-read-private: ''
    type: oauth2
paths:
  '/browse/categories/{category_id}':
    get:
      operationId: browseCategoriesByCategoryId
      description: |
        [Get a Single Browse Category](https://developer.spotify.com/web-api/get-category/)